name: "Upstream Sync"
on:
  schedule:
    - cron: "0 */4 * * *" # 每 4 小时运行一次

  workflow_dispatch:
    inputs:
      sync_test_mode:
        description: "Fork Sync Test Mode"
        type: boolean
        default: false

jobs:
  call-workflow-sync:
    uses: aliuq/workflows/.github/workflows/sync.yml@master
    with:
      ref: main
      target_sync_branch: main
      upstream_sync_repo: jaywcjlove/reference
      upstream_sync_branch: main
      sync_test_mode: ${{ inputs.sync_test_mode }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
