name: "Upstream Sync"
on:
  schedule:
    # - cron: "0 */4 * * *" # 每 4 小时运行一次
    # - cron: "0 */4 * * *" # 每 4 小时运行一次
    # 每 2 分钟运行一次
    - cron: "*/2 * * * *"

  workflow_dispatch:
    inputs:
      debug:
        description: "Fork Sync Test Mode"
        type: string
        default: 'false'

jobs:
  call-workflow-sync:
    uses: aliuq/workflows/.github/workflows/sync.yml@master
    with:
      ref: main
      target_sync_branch: main
      upstream_sync_repo: jaywcjlove/reference
      upstream_sync_branch: main
      debug: ${{ inputs.debug }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
